### ISSUE TITLE
OOP-1-review-2022-10-16

### ISSUE THREAD

**Issue by hamerlinski** [MMichal34/PO-L12#1]
**Task 1**
- [ ] Proper communication/interaction between classes and objects is missing.
- [ ] Rename repository to **oop-put-course**
- [ ] Rename files to task1-1.cpp, task1-2.cpp, task1-3.cpp
- [ ] Format code properly
- [ ] Add file extension
- [ ] Don't use polish language
